version: '3'
services:
  # Application Dockerfile is in the same folder.
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "30000:30000"

  # db is in the db folder
  db:
    build: db/.
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - "3307:3306"
